---
- name: Add the Service Group
  group:
    name: "{{ user }}"
    state: present

- name: Add the Service User
  user:
    name: "{{ user }}"
    groups: "{{ user }}"
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "RocketMQ Service User"
    state: present

- name: install mq from binary release
  include_role:
    name: install-1.0.5
  vars:
    opts:
      pkg_name: rocketmq
      pkg_version: "{{ mq_version }}"
      pkg_type: zip
      pkg_url: "https://mirrors.tuna.tsinghua.edu.cn/apache/rocketmq/{{ mq_version }}/rocketmq-all-{{ mq_version }}-bin-release.zip"
      extracts: yes
      creates: "bin/mqbroker"
      target_owner: "{{ user }}"
      target_group: "{{ user }}"
      bin_path:

- name: mv detail to ex-path
  copy:
    src: "/opt/{{ item }}/{{ mq_version }}/{{ item }}-all-{{ mq_version }}-bin-release/"
    dest: "/opt/{{ item }}/{{ mq_version }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: preserve
    remote_src: yes
    directory_mode: u=rwx,g=rwx,o=
  with_items:
    - "{{ user }}"

- name: install tools
  apt:
    update_cache: yes
    name: ['openjdk-8-jdk','jq']
    state: present

- name: set security limits
  copy:
    dest: "/etc/security/limits.d/rocketmq.conf"
    content: "rocketmq    soft  core  unlimited"

- name: Replace broker nameserver start jvm_opts
  replace:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - path: /opt/rocketmq/current/bin/runserver.sh
      regexp: '-server -Xms4g -Xmx4g -Xmn2g'
      replace: ''
    - path: /opt/rocketmq/current/bin/runserver.sh
      regexp: '\${GC_LOG_DIR}'
      replace: '/data/nameserver/logs'
    - path: /opt/rocketmq/current/bin/runbroker.sh
      regexp: '-server -Xms8g -Xmx8g -Xmn4g'
      replace: ''
    - path: /opt/rocketmq/current/bin/runbroker.sh
      regexp: '\${GC_LOG_DIR}'
      replace: '/data/broker/logs'

- name: disable auto start
  systemd:
    name: "{{ svc_name }}"
    state: stopped
    masked: yes
  loop:
  - rocketmq-broker
  - rocketmq-nameServer
  loop_control:
    loop_var: svc_name
