---
- name: copy conf files
  copy:
    src: files/opt/app/
    dest: /opt/app/
    owner: "{{ user }}"
    group: "svc"
    mode: preserve
    directory_mode: u=rwx,g=rx,o=r

- name: install confd files
  include_role:
    name: confd-files-1.0.8
