---
- name: copy conf files
  copy:
    src: files/opt/app/
    dest: /opt/app/
    owner: "rocketmq"
    group: "svc"
    mode: preserve
    directory_mode: "750"

- name: install confd files
  include_role:
    name: confd-files-1.0.8
