[template]
src = "nameServer.sh.tmpl"
dest = "/opt/app/current/bin/tmpl/nameServer.sh"
mode = "0700"
keys = [
  "/",
]
reload_cmd = "/opt/app/current/bin/tmpl/nameServer.sh; appctl reload rocketmq-nameServer"
