---
- name: common setup
  hosts: all
  strategy: free
  vars:
    target_env: "{{ lookup('env', 'target') }}"
  tasks:
  - include_role:
      name: "{{ service_name }}"
    loop:
    - disable-apt-jobs
    - disable-motd
    - app-agent
    - appctl
    - arping
    - caddy
    - rocketmq
    - node-all
    - node-client
    - rocketmq-console
    - node-console
    - node-broker
    - node-namesrv
    loop_control:
      loop_var: service_name
