---
- name: prepare service directories
  file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "svc"
    state: directory
  with_items:
    - "/opt/app"

- name: set JAVA_HOME
  copy:
    dest: /etc/profile.d/java-path.sh
    content: |
      JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"

- name: install confd files
  include_role:
    name: confd-files-1.0.8
