---
- name: prepare service directories
  file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
  with_items:
    - "/opt/app"

- name: copy conf files
  copy:
    src: files/opt/app/
    dest: /opt/app/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: Replace caddy service
  replace:
    path: "/lib/systemd/system/caddy.service"
    regexp: '=caddy'
    replace: '={{ user }}'

- name: install confd files
  include_role:
    name: confd-files-1.0.7
