---
- name: prepare service directories
  file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
  with_items:
    - "/data/broker"
    - "/data/console"
    - "/data/nameserver"
    - "/opt/app"

- name: Replace caddy service
  replace:
    path: "/lib/systemd/system/caddy.service"
    regexp: '=caddy'
    replace: '={{ user }}'

- name: install confd files
  include_role:
    name: confd-files-1.0.2