---
- name: prepare service directories
  file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "svc"
    state: directory
  with_items:
    - "/opt/app"

- name: Add the user to svc
  user:
    name: "{{ item }}"
    groups: "svc"
    append: yes
  with_items:
    - "caddy"
    - "root"

- name: set JAVA_HOME
  copy:
    dest: /etc/environment
    content: |
      JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
      PATH="$JAVA_HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

- name: install confd files
  include_role:
    name: confd-files-1.0.8
